import type { GetStaticProps, NextPage } from 'next'
import { InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { getSession, signOut } from 'next-auth/react'
import axios from 'axios'

import styles from '../styles/Home.module.css'


type Keys = {
  CLIENT_ID: string
  CLIENT_SECRET: string
}

const Home: NextPage = ({ CLIENT_ID, CLIENT_SECRET }: InferGetStaticPropsType<typeof getStaticProps>) => {
  const handleSignOut = async () => {
    const session = await getSession()
    if (session) {
      const res = await axios({
        method: 'post',
        url: process.env.NEXT_PUBLIC_URL_API + '/auth/revoke-token',
        data: {
          client_secret: CLIENT_SECRET,
          client_id: CLIENT_ID,
          token: session.refreshToken
        }
      })
    }

    const result = await signOut({ redirect: false })
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
        <div>
          <button
            onClick={handleSignOut}
            className="rounded-md border px-4 py-2"
          >
            Cerrar Sesión
          </button>
          <Link
            href="/login"
          >
            <a
              className="rounded-md border px-4 py-2"
            >
              Iniciar Sesion
            </a>
          </Link>
          <Link
            href="/signup"
          >
            <a
              className="rounded-md border px-4 py-2"
            >
              Registrar Usuario
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const CLIENT_SECRET = process.env.CLIENT_SECRET
  const CLIENT_ID = process.env.CLIENT_ID
  const contextKeys: Keys = {
    CLIENT_SECRET: CLIENT_SECRET || '',
    CLIENT_ID: CLIENT_ID || ''
  }

  return {
    props: contextKeys,
  }
}

export default Home
